# Configuración compartida para todos los perfiles
spring:
  profiles:
    active: local
  main:
    lazy-initialization: true
  h2:
    console:
      enabled: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password: sa
    initialization-mode: always



